### PR TITLE
USWDS - Forms: Update required field guidance.

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

Closes uswds/uswds#3691, #1163, and uswds/uswds#3295.

### Preview link
[Updated guidance →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-required-fields/components/form-templates/)

## Additional information

Updates guidance for required fields.

- Removed optional guidance from address form
- Added more general required field guidance at the top

## Related PRs
[Template updates](https://github.com/uswds/uswds/pull/3828)

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [x] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by allie-shaw** [comment]
Looks good to me!

**Review by allie-shaw — APPROVED** [review]
Looks good to me.

**Comment by mejiaj** [comment]
Maybe we should close this in favor of a new branch based on 2.11.0 component page updates.

**Comment by maya** [comment]
The linked example doesn't have the red required asterisk style, is that intentional?
Screen Shot 2021-03-17 at 12 46 16 PM

Also, what are the two dots underneath it for? @mejiaj

**Comment by mejiaj** [comment]
The dots are for the `<abbr>` element. This branch is pretty old and only mentions the guidance on 1 template. Which is why I think we should close this and re-think the approach.

It's red, like it should be, on the latest live branch.

**Comment by maya** [comment]
Oh yeah, there's no dots on the live site, probably just bc it's out of date.

**Comment by mejiaj** [comment]
Closing as outdated.

**Pull request closed without merging**
