### PR TITLE
USWDS-Site - Changelog: Add component changelogs (Phase 1)

### LINKED ISSUE #1883: USWDS-Site - Changelog: Release component changelogs (Phase 1)
Items that must be completed before release:
- [x] #1865 
- [x] #1864
- [x] #1863 
- [x] #1869
- [x] Integrate markdownify (Added in https://github.com/uswds/uswds-site/pull/1871)
- [ ] Final proofread/copyedit

### PR DESCRIPTION
**Pull request by amyleadem**
## Summary
This update adds release data to component page changelogs. The data added covers release notes from 3.2.0 --> 2.11.0.

## Related issue
Closes #1883

## Preview links
- [Accordion](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/accordion/)
- [Alert](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/alert/)
- [Banner](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/banner/)
- [Breadcrumb](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/breadcrumb/)
- [Button group](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/button-group/)
- [Button](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/button/)
- [Card](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/card/)
- [Character count](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/character-count/)
- [Checkbox](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/checkbox/)
- [Collection](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/collection/)
- [Combo-box](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/combo-box/)
- [Date picker](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/date-picker/)
- [Date range picker](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/date-range-picker/)
- [File input](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/file-input/)
- [Footer](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/footer/)
- [Header](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/header/)
- [Icon list](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/icon-list/)
- [Icon](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/icon/)
- [Identifier](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/identifier/)
- [Input prefix/suffix](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/input-prefix-suffix/)
- [Link](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/link/)
- [List](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/list/)
- [Memorable date](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/memorable-date/)
- [Modal](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/modal/)
- [Pagination](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/pagination/)
- [Process list](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/process-list/)
- [Prose](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/prose/)
- [Radio buttons](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/radio-buttons/)
- [Range slider](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/range-slider/)
- [Search](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/search/)
- [Select](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/select/)
- [Side navigation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/side-navigation/)
- [Site alert](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/site-alert/)
- [Step indicator](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/step-indicator/)
- [Summary box](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/summary-box/)
- [Table](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/table/)
- [Text input](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/text-input/)
- [Time picker](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/time-picker/)
- [Tooltip](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/tooltip/)
- [Typography](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/typography/)
- [Validation](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/al-changelog-main/components/validation/)

## Tasks
Items that must be completed before release:
- [x] #1868 
- [x] #1876
- [x] #1871
- [x] #1890
- [x] Integrate markdownify
    - Added in #1871
- [x] Final proofread on all changelogs for consistency and errors

## Testing and review
PR numbers, release numbers, release dates have been verified in PRs #1865, #1864, and #1863, but a second look would be helpful. 

Please review that there are no typos or grammatical/spelling errors.

---

Before opening this PR, make sure you’ve done whichever of these applies to you:

- [x] Confirm that this code follows the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [ ] Run `npm test` and confirm that all tests pass.

### CODE REVIEW

**Comment by amyleadem** [comment]
### Notes
- Make "affects" tags display alphabetically?

**Comment by amyleadem** [comment]
Checking the following items:
- [ ] All summaries are written in the past tense, led with common verbs.
- [ ] All summaries end with a period.
- [ ] All spelling is correct.
- [ ] Component names are lowercase.

**Comment by amyleadem** [comment]
@bonnieAcameron Can you proofread the changelog items on these pages to check for errors? 

Some background - this content is primarily pulled directly from our release notes, but may have been altered to fit a standard format (outlined in the [CHANGELOG-README](https://github.com/uswds/uswds-site/pull/1870/files#diff-0bace2ed80976d536baf0a44e4d722dbe3ac44ea0554e3976aecf0f79be4db81)). I have done a pass to confirm that the dates, release numbers, and content is accurate. 

I believe the primary remaining effort should be to just confirm spelling, punctuation, and capitalization, but if you see opportunities to improve clarity, please feel free to flag it! Please let me know if you have questions.

**Comment by amyleadem** [comment]
Putting this in draft mode to resolve some errors.

**Review by thisisdano — APPROVED** [review]
Nice work

**Review by bonnieAcameron — COMMENTED** [review]
This looks AMAZING, Amy! The only thing I found is a capitalization error that is pulled in a few times from Pulling from 2.12.2 in [uswds#4329](https://github.com/uswds/uswds/pull/4329), where "design system" is lowercase and should be capitalized, since it's referring to a proper noun design system, in the same way that The President is capitalized when referring to a specific, acting president.

**Review by bonnieAcameron — APPROVED** [review]

**Comment by amyleadem** [comment]
Closing because these changes were included and merged in #1889.

**Pull request closed without merging**
