### PR TITLE
Integrate UDWDS default fonts and update component pages

### LINKED ISSUE #706: natives@1.1.6 hack required after installing beta 5
We had to install `natives@1.1.6` after using USWDS Beta 5. This is a weird hack that we don't want want USWDS users to have to worry about. We have no issues building locally without the haclk, and no issues on Federalist — but we were getting fails on Circle CI. 

The issue and its solution can be seen here: https://github.com/gulpjs/gulp/issues/2246

Will upgrading to Gulp 4.x fix this? And if so, do we need to upgrade both here and in the `uswds` repo?

### LINKED ISSUE #718: Audit docs for missing or out-of-date content
Let's look through the docs to identify any items that are out of sync with USWDS 2.0 — or that have been flagged as missing or to come. Let's write issues around any instances we find and work to update all these issues asap.

### LINKED ISSUE #722: USWDS site and fractal using different sans fonts
The demo components on the USWDS site are using Public Sans while the fractal size is using Source Sans Pro for the sans serif font. They are both using Merriweather for the serif. Should they be using the same sans serif font?

Fractal site (Source Sans Pro): https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/preview/layout--docs.html
USWDS docs site (Public Sans): https://v2.designsystem.digital.gov/page-templates/docs/

### LINKED ISSUE #728: Blog looks a bit gnarly
More context TK

### PR DESCRIPTION
**Pull request by thisisdano**
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-font-do-si-do/)

This is an overstuffed PR.

- Uses our default faces for components
- Updates the styling on component pages
- Uses a new +/- for component and nav accordions
- Uses a blue accordion bar for component code to make it more prominent
- Changes the component `documentation` accordion to `usage` since the page itself is the overall documentation and the accordion content is about how to use it
- Reorganizes components in alpha order
- Added short intros to most usage bullet sections for scan-ability
- Fixed the `About USWDS` sidenav
- Reinstated the sidenav for blog posts
- Updated the typography/typesetting sections
- Add line numbers to code samples
- Fix header display in IE
- More consistent use of `USWDS`
- Improve documentation around a utility's manual values

- - -
Fixes https://github.com/uswds/uswds/issues/2925
Fixes #728 
Fixes #722 
Fixes #706 
Fixes #718

### CODE REVIEW

**Comment by maya** [comment]
I know you're still working on this but noticed the accordion width got too [narrow](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-font-do-si-do/components/form-controls/) for code samples and docs:

Screen Shot 2019-03-20 at 1 53 23 PM

**Comment by thisisdano** [comment]
I _would_ like to try and narrow these, but I also see that the rendering is worse because they don't indent properly for long lines. Is there anything Jekyll can do improve wrapping with indents? (This would be an improvement, particularly for mobile, even with a wider desktop box.)

**Comment by maya** [comment]
I see some components are full-width (e.g. [header](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-font-do-si-do/components/header/)) while the page template is narrow:
Screen Shot 2019-03-20 at 3 02 04 PM
Screen Shot 2019-03-20 at 3 06 26 PM

When it's full-width, it gives a more accurate representation of the component.

**Comment by thisisdano** [comment]
Yeah, I'd defaulted to narrow unless it really distorted the component (like `footer` for instance). It did not seem like showing the templates at wider width gave a better indication of their final look-and-feel as 75% size inside a text column didn't seem more accurate than 50% inside a text column— the demo is the truly accurate example.

I could see making the template examples wider, but I could also see making them longer and showing perhaps the entire template page.

**Comment by maya** [comment]
I'm working on updating screenshots in #729, so let me know which you'd rather go with (wider or longer) page template screenshots.

**Comment by thisisdano** [comment]
Let's try longer and see how it looks. It if looks bad, we can always crop them.

**Comment by maya** [comment]
Longer is done in #729.

**Comment by maya** [comment]
Seems like work is still happening on this even though we're tagged for review. Feel free to ping when it's ready.

**Comment by thisisdano** [comment]
It's done.

**Pull request merged**
