### PR TITLE
[v2] Remove infinite loop redirect

### PR DESCRIPTION
**Pull request by thisisdano**
Remove infinite loop redirect from download page

### CODE REVIEW

**Comment by thisisdano** [comment]
huh. what the heck happened here?

**Comment by thisisdano** [comment]
Maybe something got hosed in the that last merge conflict...?

**Comment by thisisdano** [comment]
Yeah, it's no longer running the gulp sass as part of the build process...

**Comment by thisisdano** [comment]
The old strict mimetype strikes again... :cool:

> Refused to apply style from 'https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-advanced-settings/assets/css/styleguide.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by maya** [comment]
This has some extraneous changes, so done in 58b8ec9244f4839edf0257afb69796948c4ba67d.

**Pull request closed without merging**
