### PR TITLE
USWDS - Homepage: update hero CTAs.

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

Part of sprint goal to [update homepage](https://github.com/orgs/uswds/projects/1#card-55947663). This PR updates the 2 hero CTAs.

### Preview link
[Preview link →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-homepage-ctas/)

## Additional information

**Old**
designsystem digital gov_

**New**
localhost_4000_

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by KMullan944 — APPROVED** [review]
I couldn't actually click on those CTA buttons but hope they go to the right place? :) Copy on each looks good

**Comment by mejiaj** [comment]
> I couldn't actually click on those CTA buttons but hope they go to the right place? :) Copy on each looks good

Faster than me on the review, Federalist just finished building the [preview](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-homepage-ctas/).

**Review by KMullan944 — APPROVED** [review]
Changes look good -- reviewed new copy on buttons and tested preview -- good to go! Thank you

**Comment by katharine-carr** [comment]
Looks good to me! This small change makes a big difference IMO!

**Review by katharine-carr — APPROVED** [review]
I like it! Changes for the better. Good to go.

**Comment by thisisdano** [comment]
Should we say `Why use USWDS?` for the second button, to be clearer? You could read `Why USWDS?` as "Why does the design system exist?"

**Comment by sofya-UX** [comment]
@thisisdano my concern with adding "use" into the second CTA is that it will make the  whole button much longer. Also, the "Why USWDS?" is more intriguing and might generate more clicks.

**Comment by thisisdano** [comment]
I don't want the button to be intriguing, I want it to be clear. There is enough room to make it more clear (using only 4 characters), so I think we should.

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
