### PR TITLE
[ci] Fail CI on SCSS compile error

### PR DESCRIPTION
**Pull request by el-mapache**
## Description

Since we are running our gulp tasks in parallel, scss failing to compile won't cause the build step to fail on CI. It will fail subsequent steps when the css file isn't found. This can be confusing. So, fail the build immediately if scss cant compile

### CODE REVIEW

**Comment by thisisdano** [comment]
@el-mapache It's nice, when running `npm run watch`, to keep the watch script running through the sass fail so we don't have to keep restarting it. But we _do_ want that hardfail in the federalist build. Is there any good way to apply this bailout only when running the federalist build script?

**Comment by el-mapache** [comment]
@thisisdano Good point, I didn't check the watch. I can add a `development` env variable which bypasses the call to `process.exit`

**Comment by el-mapache** [comment]
@thisisdano would you mind taking a peek and see if this does what you want? I tested it and it seems to keep the `watch` running even if the scss is bogus, which I believe is the desired behavior!

**Comment by thisisdano** [comment]
This looks great from the `watch` side — I haven't tested on federalist, but if you have, this is good to go.

**Comment by el-mapache** [comment]
@thisisdano I havent tested it there, but nothing changed from that perspective beyond the change to fail the build if the scss is invalid.

**Pull request merged**
