### PR TITLE
Update design assets

### PR DESCRIPTION
**Pull request by donjo**
Updates the assets from uswds/uswds-assets

### CODE REVIEW

**Comment by maya** [comment]
Did we already run the release on `uswds-assets`? https://github.com/uswds/uswds-assets#generating-archive-files

**Comment by donjo** [comment]
@maya yeah that was the command I ran to get the zipped assets that are included in this PR

**Comment by maya** [comment]
So when you run the release on `uswds-assets` to generate the zip files, it adds the zip file to a different project `uswds-site` automatically? The process isn't super clear in the documentation.

**Comment by donjo** [comment]
That was a manual part of the process that I had to do. I added a line in the asset readme to mention how the files make their way to this site in the [following PR](https://github.com/uswds/uswds-assets/pull/49). The release command just generates files for release but doesn't make any assumptions about how/where you will release (similar to the release command in the USWDS core project)

**Pull request merged**
