### PR TITLE
Import uswds readme for Developers page

### PR DESCRIPTION
**Pull request by hursey013**
Import README from https://github.com/uswds/uswds/ into the developers page (to remove duplication).

Fixes https://github.com/uswds/uswds-site/issues/538

Preview: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/bh-install-readme/getting-started/developers/

### CODE REVIEW

**Comment by maya** [comment]
@hursey013 yes, let's add them to the README too. May have to combine the two JS sections into one.

**Comment by hursey013** [comment]
@maya Updated the main repo's README to add the missing content: https://github.com/uswds/uswds/pull/2462

**Comment by maya** [comment]
@hursey013 this still needs to address #1: The numeric steps in "Install using npm" all start at 1 instead of being an ordered list. Need to follow the formatting of the removed content to get it to display correctly.

Were you planning on opening a separate PR for it?

**Comment by hursey013** [comment]
This just imports the README as is from `uswds`, so it is already a properly markdown formatted file, I don't have the ability to change the formatting of particular sections. I'm going to try tweaking the source README in `uswds` in order to add some additional indentation to the lists, and maybe that'll do the trick? Otherwise it's likely some difference between the way github and jekyll render markdown.

**Pull request merged**
