### PR TITLE
USWDS-Site - Ruby: Use `3.3.4`

### LINKED ISSUE #1759: USWDS-Site - Feature: Update ruby version
### Is your feature request related to a problem? Please describe.

[Ruby 3.1.2 has been released](https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-1-2-released/) with some security fixes. We should update to get those security and any performance benefits.

### Describe the solution you'd like

Check latest stable release on https://www.ruby-lang.org/en/downloads/releases/.

### Describe alternatives you've considered

_No response_

### Additional context

We should also double-check the circleci config 

https://github.com/uswds/uswds-site/blob/2b92564fc0be666b3573bbee6ce869ee1207a3ab/.circleci/config.yml#L9

And update the `.ruby-version`.
https://github.com/uswds/uswds-site/blob/2b92564fc0be666b3573bbee6ce869ee1207a3ab/.ruby-version#L1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate feature requests.

### PR DESCRIPTION
**Pull request by mahoneycm**
# Summary

Sets ruby version to `3.3.4` and updates relevant gems.

## Related issue

Closes #1759

Updating in an effort to resolve the following dependabot alerts: 
- https://github.com/uswds/uswds-site/security/dependabot/71
- https://github.com/uswds/uswds-site/security/dependabot/70
- https://github.com/uswds/uswds-site/security/dependabot/69

## Preview link

Preview link →

## Problem statement

Ruby `3.1.x` versions have stopped receiving updates as of 2024-04-01. Additionally, REXML was causing 

## Solution

Update ruby version to `3.3.4`.

## Major changes

**Replaced `File.exsits?` with `File.exist?`** 
Starting in **Ruby 3.2.0** the `exists?` (pluralized) alias for `exist?` seems to has been removed.

## Testing and review

On your local machine, install and use Ruby `3.3.4`

1. Pull down and checkout this branch
2. Run `rvm install 3.3.4`.
  - If you have an install installing you may need to install and specify the OpenSSL version
  - `rvm install 3.3.4 -- --with-openssl-dir=$(brew --prefix openssl@1.1)`
3. Run `rvm use 3.3.4`
4. Confirm the correct ruby version is being used by running `ruby -v`
5. Run `gem install bundler` to confirm that the correct bundler version is used
6. Run `bundle install` to install all gems and confirm there are no errors or additional gems
7. Run `npm start` and confirm the site builds without errors

>[!IMPORTANT]
>Any additional PLATFORMS added to the gemfile should captured in #2577 and be ignored in this PR

### Testing checklist

- [ ] Gems install without error.
- [ ] Site builds without error.
- [ ] Jekyll start and build commands run without error.
- [ ] No errors in `ci/circleci: install_ruby_deps`

## Dependency updates

| Dependency name              | Previous version | New version |
| ---------------------------- | :--------------: | :---------: |
| Ruby |     `3.1.2`      |   `3.3.4`   |

### CODE REVIEW

**Review by mejiaj — COMMENTED** [review]
@mahoneycm is this just a test PR or is it meant to close #1759?

I see a commit e9ffb4a updates bundler, but `.bundler-version` shows `2.3.7`.

https://github.com/uswds/uswds-site/blob/b5f65dc30837ebee7c79a763500158f6d07a33bd/.bundler-version#L1

**Comment by mahoneycm** [comment]
@mejiaj This was intended to close #1759 but I ran into CIrcleCI issues with the following error:

`Could not find sass-embedded-1.69.3-x86_64-linux in any of the sources`

We should maintain bundler `2.3.7` because that resolved issues we found while completing the [May POAM](https://github.com/uswds/uswds-site/pull/2673)

I'm curious if reverting the bundler version to `2.3.7` will resolve the issues 🤔 

Hoping to return to this after my time away

**Review by mejiaj — COMMENTED** [review]
@mahoneycm thanks for updating Ruby. Successfully updated and built using:
```sh
rvm install 3.3.4 --with-openssl-dir=$(brew --prefix openssl)
```

Would you mind updating the PR and its description? There are still references to an older version `3.2.3`.

No issues found on site (double-checked generated pages like `/about/security` too.

**Review by mejiaj — APPROVED** [review]

**Review by amyleadem — APPROVED** [review]
LGTM!

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
