### PR TITLE
Fix master + v2 merge conflicts

### PR DESCRIPTION
**Pull request by maya**
This merged `master` into `v2` and fixed merge conflicts. 

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/v2-fix-master-merge-conflicts/)

### CODE REVIEW

**Comment by thisisdano** [comment]
I was just thinking about that range slider....

**Comment by maya** [comment]
I kept `_includes/banner-news.html` in, in case we wanted to use it for other news, but took it out of the landing page template.

**Comment by thisisdano** [comment]
I can hop in there and tidy up the range slider docs, but otherwise this is probably good.

**Comment by maya** [comment]
@thisisdano Please go ahead.

**Pull request merged**
