### PR TITLE
USWDS-Site - Links: Update broken CDC links

### LINKED ISSUE #2686: USWDS-Site - HTMLProofer: Broken CDC Links
# Summary

HTMLProofer is returning 6 new 404 links from the CDC website.

## Error message

```js
For the Links > External check, the following failures were found:

* At ./_site/components/link/index.html:3726:

  External link https://www.cdc.gov/cancer/skin/basic_info/sun-safety.htm failed (status code 404)

* At ./_site/components/link/index.html:3735:

  External link https://www.cdc.gov/cancer/skin/basic_info/sun-safety.htm failed (status code 404)

* At ./_site/patterns/create-a-user-profile/gender-identity-and-sex/index.html:2865:

  External link https://www.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/collecting-sexual-orientation.html failed (status code 404)

* At ./_site/patterns/create-a-user-profile/gender-identity-and-sex/index.html:3338:

  External link https://www.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/collecting-sexual-orientation.html failed (status code 404)

* At ./_site/patterns/create-a-user-profile/gender-identity-and-sex/index.html:3349:

  External link https://www.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/affirmative-care.html failed (status code 404)

* At ./_site/together/findings/index.html:803:

  External link https://www.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/collecting-sexual-orientation.html failed (status code 404)


HTML-Proofer found 6 failures!
```

## Proposed solution

Find replacement links for each of the links and update to resolve errors

### PR DESCRIPTION
**Pull request by mahoneycm**
# Summary

Replaced broken CDC links due.

> [!IMPORTANT]
The following two links are temporary snapshots of pages that don’t exist anymore. They will be taken down after November 2024. 
> - [Patient-Centered Care for Transgender People: Recommended Practices for Health Care Settings](https://snapshot2024.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/affirmative-care.html)
> - [Collecting Sexual Orientation and Gender Identity Information](https://snapshot2024.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/collecting-sexual-orientation.html)
>
> I have reached out to [dcm@cdc.gov](mailto:dcm@cdc.gov) to ask for more a more permanent replacement
> 

## Related issue

Closes #2686

## Preview link

- [Link component page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-links-cdc-temp/components/link/)
- [Inclusive design patterns findings citations →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-links-cdc-temp/together/findings/)
- [Gender identity and sex →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-links-cdc-temp/patterns/create-a-user-profile/gender-identity-and-sex/)

## Problem statement

The CDC recently updated their site which caused older links to break. HTMLProofer caught the related 404 errors.

## Solution

Replace links with their updated counterparts where available. Add temporary snapshot links to removed content for the links that are not

### Confirm link replacements are appropriate

| Page name | Original link (Web archive) | Replacement link |
|--------|--------|--------|
| Sun safety | https://www.cdc.gov/cancer/skin/basic_info/sun-safety.htm |https://www.cdc.gov/skin-cancer/sun-safety/ |
| Collecting Sexual Orientation and Gender Identity Information | https://www.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/collecting-sexual-orientation.html | https://snapshot2024.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/collecting-sexual-orientation.html |
| Patient-Centered Care for Transgender People: Recommended Practices for Health Care Settings | https://www.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/affirmative-care.html |  https://snapshot2024.cdc.gov/hiv/clinicians/transforming-health/health-care-providers/affirmative-care.html |

### Confirm new links work

1. Visit the following pages and verify links are working as expected.
    1. [Link component page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/cm-links-cdc-temp/components/link/) - CDC Sun care links
    2. [Inclusive design patterns findings citations](https://designsystem.digital.gov/together/findings/#section_6) - CDC snapshot links in sitations
    3. [Gender identity and sex](https://designsystem.digital.gov/patterns/create-a-user-profile/gender-identity-and-sex/) 
        1. HIV Nexus Clinician Resources link
        2. Collecting sexual orientation and gender identity information resource link
        3. Patient centered care for transgender people: recommended practices for health care settings resource link
5. Confirm there are no HMTL Proofer errors

### CODE REVIEW

**Review by amyleadem — COMMENTED** [review]
These updates look good to me! 

However, I noticed that there is a new html proofer failure on https://pubs.er.usgs.gov/. It returns a 301 and looks like it has been moved to https://pubs.usgs.gov/. However, this new url is returning a mix of both 500 and 502 status codes. 

The [wayback machine](https://web.archive.org/web/20240000000000*/https://pubs.usgs.gov/) seems to have captured a working site earlier today, so I'm guessing we just need to wait it out. 

- [ ] Confirm html proofer issues are fixed
- [x] Confirm the links point to appropriate replacements
- [x] Confirm there is no need for a changelog

**Comment by mahoneycm** [comment]
@amyleadem Hmm I haven't been able to reproduce yet. If it's `301` then we should probably update the link to point to its permanent address.

It also looks like as of this morning uxpro.cc is down and causing an additional 404 error on the phone number patterns page. Hopefully this is a temporary outage but I'll keep my eye on it 🧐

**Review by amyleadem — APPROVED** [review]
Looks like the HTML proofer tests are now passing. LGTM!

**Review by annepetersen — APPROVED** [review]

**Comment by thisisdano** [comment]
Merging over pa11y crash

**Pull request merged**
