### PR TITLE
Adds linting to `npm test` command

### LINKED ISSUE #623: Error when we have scss-lint issues
Currently, CircleCI will allow us to have stylelint issues (it won't fail), though we shouldn't be able to.

### PR DESCRIPTION
**Pull request by el-mapache**
## Description
 
Now our circle jobs will fail when errors are encountered in our `.scss` files

Fixes #623.

### CODE REVIEW

**Comment by maya** [comment]
I see it found an scss issue in the [CircleCI test](https://circleci.com/gh/uswds/uswds-site/1837?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), but did not fail the build:

```
[22:47:53] 1 issues found in /home/circleci/project/css/styleguide.scss
[22:47:53] styleguide.scss:8 [W] FinalNewline: Files should end with a trailing newline
```

And I would expect it to fail the build.

**Comment by maya** [comment]
On a different rule it failed the build (which is what we want), so going to guess this was just a fluke or does not fail the build on the rule above. https://circleci.com/gh/uswds/uswds-site/1838

**Comment by el-mapache** [comment]
@maya that is a warning, we currently only have it set up to fail on errors. However, we can definitely update it to fail on any issue!

**Comment by maya** [comment]
@el-mapache I figured it was something like that. Yeah, it should probably fail on that too.

**Pull request merged**
