### PR TITLE
USWDS - Banner: Add intro paragraph.

### LINKED ISSUE #1088: Intro paragraph for Banner component
New intro paragraph for Banner has been created. See preview [here](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-banner-intro/components/banner/#site-component-intro) 

- [X] create [draft intro](https://docs.google.com/document/d/1I6bHDbbLz28Hbamr2mL7ZRSSVqe7Wy5vv_iVleKRtSc/edit#heading=h.cwqvrw8xqdb1)
- [x] PR created: https://github.com/uswds/uswds-site/pull/1105
- [x] align w comms plan
- [x] client review 2.17
- [x] update and finalize PR

**DOD**
- [x] all tasked are complete
- [ ] new paragraph is published to banner component page

### PR DESCRIPTION
**Pull request by mejiaj**
## Preview
[Banner →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-banner-intro/components/banner/#site-component-intro)

## Description

Resolves #1088. Added intro paragraph to Banner component.

## Additional information

Decreased the size of the `h2` with `font-body-md` because it seemed too big.

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by mejiaj** [comment]
Possible false positive in `npm test` to unrelated page (`form-controls/10-range-input`)

```bash
> uswds-site@ crawl /Users/jamesmejia/web/uswds-site
> node config/crawl.js

Error: duplicate id attrs found at /form-controls/10-range-input/:
  range-slider
1 error(s) and 0 warning(s) found.
Alas.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uswds-site@ crawl: `node config/crawl.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uswds-site@ crawl script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jAigret-Bix** [comment]
@mejiaj Could you update this PR? There are two sentence to add to the top of the intro as indicated in this [Gdoc](https://docs.google.com/document/d/1I6bHDbbLz28Hbamr2mL7ZRSSVqe7Wy5vv_iVleKRtSc/edit#). new sentences are highlighted in yellow

**Comment by mejiaj** [comment]
@jAigret-Bix updated. You can view it on the preview link above.

**Comment by thisisdano** [comment]
Closed in favor of #1136

**Pull request closed without merging**
