### PR TITLE
USWDS-SITE-850: Add v1.x docs link.

### LINKED ISSUE #850: Link to v1 docs is hidden
It needs to be in a more obvious location.

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

Proposal that fixes #850.

image

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [x] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by afeijoo** [comment]
@mejiaj According to the site scanner, there are about [85 sites on v1](https://site-scanning.app.cloud.gov/searchUSWDS/?q=0&sort=Domain&version=detected+versions&date=Scan+Date&agency=All+Agencies&domaintype=All+Branches&hitsperpage=200). Based on these data, the hero may be too prominent. 

As a first step, can we add links to https://v1.designsystem.digital.gov/ from all mentions of v1 on the site such as:
* https://designsystem.digital.gov/documentation/migration
* https://designsystem.digital.gov/documentation/developers/#long-term-support-of-v1x

**Comment by mejiaj** [comment]
@afeijoo, I see. Do you imagine this change on [v1](https://v1.designsystem.digital.gov/) like a new section that displays migration and long term support more prominently?

**Comment by afeijoo** [comment]
@mejiaj  What do you think of adding a link to http://v1.designsystem.digital.gov/ from all references to `v1` on [For developers](https://designsystem.digital.gov/documentation/developers/#long-term-support-of-v1x) and [Migrating to USWDS 2](https://designsystem.digital.gov/documentation/migration/)?

As a visitor on the [Migrating to USWDS 2](https://designsystem.digital.gov/documentation/migration/) and [For developers](https://designsystem.digital.gov/documentation/developers/#long-term-support-of-v1x) pages
I want to follow links to v1 documentation at http://v1.designsystem.digital.gov/
So I can learn more about v1

**Comment by mejiaj** [comment]
@afeijoo, I've updated docs on [Migration](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/feature/USWDS-SITE-850/documentation/migration/)

I've also opened up a PR on USWDS to link 1.x because that feeds the long term support for 1.x on `For Developers`. That's linked [here](https://github.com/uswds/uswds/pull/3399).

**Comment by thisisdano** [comment]
I think it's worth trying to add a link into the footer. I'll push a commit to test this.

**Comment by thisisdano** [comment]
Added a footer link banner: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/feature/USWDS-SITE-850/

@afeijoo and @mejiaj Check it out and lmk if it works for you

**Comment by mejiaj** [comment]
Doesn't stand out _too_ much, looks good to me.

**Pull request merged**
