### PR TITLE
USWDS-Site: Use node lts 20

### PR DESCRIPTION
**Pull request by mejiaj**
# Summary

**Use latest LTS version of node.** Update package dependencies and repo to use the latest LTS version of node. Prevents compatibility issues with cloud pages.

## Related issue

Related to https://github.com/uswds/uswds/issues/5010. Extension of #2304.

## Preview link

[Preview link [homepage]](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/jm-feature-node-20-update/)

## Problem statement

To keep things up-to-date, secure, and functioning we need to update to latest node LTS version.

## Solution

1. Use node 20
2. Update minor and patch deps.
3. Stay on Prettier 2x version (Updating to 3 causes issues with current linting. Will address in #2357)

## Testing and review

1. No regressions in linting.
2. No regressions in compiling. 
3. No regressions with `npm install`.

## Dependency updates

| Dependency name         | Previous version |          New version          |
| ----------------------- | :--------------: | :---------------------------: |
| @uswds/compile          |      1.0.0       |             1.1.0             |
| chrome-remote-interface |      0.31.0      |            0.33.0             |
| concurrently            |      7.3.0       |             8.2.2             |
| eslint-config-prettier  |      8.5.0       |         ~9.0.0~ 9.1.0         |
| eslint-plugin-import    |      2.28.1      |       ~2.29.0~  2.29.1        |
| fancy-log               |      1.3.3       |             2.0.0             |
| postcss                 |      8.4.31      |            8.4.32             |
| postcss-csso            |      5.0.1       |             6.0.1             |
| prettier                |      2.4.1       |             2.8.8             |
| sass                    |      1.69.2      |            1.69.5             |
| snyk                    |     1.1234.0     | ~1.1246.0~ ~1.258.0~ ~1.1264.0~ 1.1266.0 |
| stylelint               |     15.10.3      |            15.11.0            |
| axe-core                |      4.8.2       |             4.8.3             |

### CODE REVIEW

**Review by mahoneycm — CHANGES_REQUESTED** [review]
## New vulnerability

Running `npm install` added a new `high` rated vulnerability.

Luckily, `npm audit fix` cleared it up and restored `0` vulnerabilities to match `main`.

We should add that to this branch to limit vulnerabilities introduced

**Review by mahoneycm — APPROVED** [review]
Lgtm! Thanks for updating

**Comment by mejiaj** [comment]
HTMLProofer is failing because of new 18F URLs for guides. Opened issue in USWDS/USWDS#5683 because README content is being pulled on developer docs.

**Comment by mejiaj** [comment]
Blocked until [USWDS - README: Update broken 18f links #5684](https://github.com/uswds/uswds/pull/5684) is merged.

**Pull request merged**
