### PR TITLE
Update template code to use fractal

### PR DESCRIPTION
**Pull request by donjo**
This updates the template code to use fractal components.

Note: Currently the page that generates the demo site under `_components/form-templates/form-templates.md` isn't using fractal code because of a problem with path to the CSS. Trying to come up with a way around that. 

fixes #452

### CODE REVIEW

**Comment by donjo** [comment]
Currently blocked until we figure out a way to not run aXe tests on these pages. Because assets live in different places in the fractal site and the docs site, a piece of the code coming from fractal returns a 404 on the docs site.

**Comment by maya** [comment]
Should we move it to icebox or backlog in the meantime?

**Comment by donjo** [comment]
moved to backlog for now

**Comment by maya** [comment]
Superceded by #572.

**Pull request closed without merging**
