### PR TITLE
USWDS-Site - Design principles: Replace dotgov.gov with get.gov

### PR DESCRIPTION
**Pull request by michelle-rago**
# Summary

Replace dotgov.gov with get.gov

## Preview link

Preview link:

### CODE REVIEW

**Review by amyleadem — APPROVED** [review]
Thanks for submitting this PR, @michelle-rago! It looks great. I added in a couple updates for additional references to dotgov.gov. Let me know if anything looks incorrect there.

**Review by michelle-rago — COMMENTED** [review]
Looks great! Thanks, @amyleadem.

**Review by mahoneycm — APPROVED** [review]
This looks good to me! Thanks so much!

- [x] Link uses redirected URL
- [x] All instances of `dotgov` have been replaced
- [x] No errors when using links

**Review by annepetersen — COMMENTED** [review]
LGTM. Thanks Michelle and all!

**Pull request merged**
