### PR TITLE
USWDS-875: Add Figma link to USWDS for Designers.

### PR DESCRIPTION
**Pull request by mejiaj**
##  Description

Resolves https://github.com/uswds/uswds-site/issues/875

## Additional information
@afeijoo edits welcome, but I wanted to make sure Maya got credit and the slack link was shown. 

Do we need to add a GA event for this outbound link? Do you know what that would look like?

[Preview 👁](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-figma-link/documentation/designers#uswds-for-designers) 

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by afeijoo** [comment]
@mejiaj There is a second Figma library at https:// figma.com/community/file/836611771720754351

A community member shared this library with us during the May 2020 USWDS monthly call. They said it is an updated version of Maya's USWDS component library and it includes Figma components and styles for all USWDS 2.0 assets. See the related blog post at https://truss.works/blog/uswds-figma-library for more information. 

@RhettSkelton Can you answer James's question, "Do we need to add a GA event for this outbound link? Do you know what that would look like?"

**Comment by mejiaj** [comment]
Updated Figma link. This latest Figma resource has Card, but I think it might need to be updated. It's also missing some of the newer form components.

I don't know if we need to add some text below saying it's a community resource and it's support may vary.

**Comment by RhettSkelton** [comment]
You need to unless you want to track how many people are interested in Figma. It doesn't hurt. Below are the only Event (Actions) being tracked as examples:
- Clicked download design files button inside site
- Clicked Download code and design files from inside site
- Clicked Read website standards from inside site
- Clicked View on Github from inside site
- Clicked download button inside site
- Clicked to view 2.0 version from inside site
- Clicked Download code from inside site
- PDF Download
- Publication Download

Google Analytic events look like this... <a href="https://figma.com/community/file/836611771720754351" onclick="ga('send', 'event', 'Viewed Figma Library', 'Clicked View Figma library from inside site')>Figma</a>

This format would match the current Event Categories and Actions; however, the format across the site doesn't necessarily follow GA best practices for Events. I don't have direct access to Google Tag Manager, but only Google Analytics.

**Comment by mejiaj** [comment]
Thanks @RhettSkelton! 

>This format would match the current Event Categories and Actions; however, the format across the site doesn't necessarily follow GA best practices for Events. I don't have direct access to Google Tag Manager, but only Google Analytics.

@afeijoo do we still want to add the GA tags based on this?

**Comment by afeijoo** [comment]
@mejiaj Let's leave off the GA tags for now. I added https://github.com/uswds/uswds-site/issues/991 to do a more comprehensive review of the settings.

**Comment by mejiaj** [comment]
Merging this based on the approval above and because it's a pretty small PR.

**Pull request merged**
