### PR TITLE
Add paragraph style docs

### PR DESCRIPTION
**Pull request by thisisdano**
[Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-docs-paragraph/utilities/paragraph-style/)

### CODE REVIEW

**Comment by maya** [comment]
The sidenav title says "Measure," but the actual title if "Maximum width (measure)." Should the sidenav be updated to match?

**Comment by thisisdano** [comment]
Updated nav in b3fc04c

**Comment by thisisdano** [comment]
@hursey013 I don't know why there are so many changes to the `package.lock` — I have no idea what that file does or what changes it, but I had a lot of shenanigans updating my node/npm and I want to make sure it didn't adversely affect something

**Comment by hursey013** [comment]
@dano I think you should be fine, but if we run into any problems we can just remove the lock file and start fresh.

**Pull request merged**
