### PR TITLE
Regularize and componentize utility docs

### PR DESCRIPTION
**Pull request by thisisdano**
This work adds the remainder of the utilities into the docs and attempts to regularize their layout, data, and markup to better allow design and content refinements down the road

[😎 Preview](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-componentize-docs/utilities/)

### CODE REVIEW

**Comment by thisisdano** [comment]
Beyond all the cosmetic, markup, and content changes to the docs, the biggest change here is a `gray-1` tint in the background of the body.

Also, the sidebar is now using a much lighter gray for its horizontal rules.

Both of these are in service of trying to keep the focus on the content of the docs. The utility docs, in particular have a lot of lines, examples, etc. The gray bg helps the white-background utility docs content pop a bit, and the light horizontal lines in the sidebar reduce the overall visual noise of the sidebar, and conflict less with the page content.

Since we already distinguish sidebar items with wide spacing — and distinguish an active item with weight and a vertical rule — the dark horizontal lines appeared to mostly add decoration without significant additional value.

- - -

**old:**

screen shot 2018-06-26 at 2 58 07 pm

- - -

**new:**

screen shot 2018-06-26 at 2 57 54 pm

**Comment by thisisdano** [comment]
Caught a few more `add-pin` references I need to remove...

**Comment by maya** [comment]
Yes, I like the new style changes.

@thisisdano did you realize that the sidebar change spilled into the actual [sidebar component page](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-componentize-docs/components/sidenav/)? Didn't you want it to be site-specific? It's not like that on the [fractal site](https://federalist-proxy.app.cloud.gov/preview/uswds/uswds/release-2.0/components/detail/sidenav--compare.html).

**Comment by thisisdano** [comment]
Yeah, that spillover was unintentional — I didn't mean to change the component itself, I meant it as a site override style

**Comment by thisisdano** [comment]
What's the best way to scope a change like that?

**Comment by maya** [comment]
@thisisdano you should scope it to that docs site sidenav by using the unique `sidenav` selector.

**Comment by thisisdano** [comment]
@maya OK side nav scoped: https://federalist-proxy.app.cloud.gov/preview/uswds/uswds-site/dw-componentize-docs/components/sidenav/

**Pull request merged**
