### PR TITLE
USWDS Site: Update labels for consistency.

### LINKED ISSUE #917: Update About labels for consistency
**Description**
As a user, I want to know where I am on the site so I can navigate with ease

**Requirement**
Update primary landing page urls, navigation labels and page titles for consistency

See attachment: URL, Primary Nav Label, Page Title and Left Navigation should all read `About Us` for consistency

Check for redirects affected by update to url

**Supporting Data**
Improve internal and external search; increase findability; establish best practice for UX and content strategy 

Screen Shot 2020-04-13 at 11 22 20 AM

### LINKED ISSUE #918: Update Design Principles labels for consistency
**Description**
As a user, I want to know where I am on the site so I can navigate with ease

**Requirement**
Rename primary navigation label to `Design principles` to make consistent with url, left nav and page title

**Supporting Data**
Improve internal and external search; increase findability; establish best practice for UX and content strategy 

Screen Shot 2020-04-13 at 11 30 18 AM

### LINKED ISSUE #919: Update Design Tokens labels for consistency
**Description**
As a user, I want to know where I am on the site so I can navigate with ease

**Requirement**
Rename left navigation label to `Design tokens` (as opposed to Overview) to make consistent across all primary landing pages within the website

**Supporting Data**
Improve internal and external search; increase findability; establish best practice for UX and content strategy 

Screen Shot 2020-04-13 at 11 31 42 AM

### LINKED ISSUE #920: Update Utilities labels for consistency
**Description**
As a user, I want to know where I am on the site so I can navigate with ease

**Requirement**
Rename left navigation label to `Utilities` (as opposed to `Overview`) to make consistent across all primary landing pages within the website

**Supporting Data**
Improve internal and external search; increase findability; establish best practice for UX and content strategy 

Screen Shot 2020-04-13 at 11 34 01 AM

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

- [x] Fixes #917
- [x] Fixes #918 
- [x] Fixes #919
- [x] Fixes #920 
 
## Additional information

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [x] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Comment by mejiaj** [comment]
Converted to draft, going to be adding the changes for Tokens and Design principles here.

**Comment by afeijoo** [comment]
@mejiaj If we want to use the default page titles, do we need to include the `Text` rows in `nav.yml`?

**Comment by mejiaj** [comment]
@afeijoo, we don't need them. By default it will use the `title` value of that page.

Updated.

**Comment by thisisdano** [comment]
While I generally like the shape of this, there are couple things I'd prefer:
1. `About us` is simply `About`
2. We use `Overview` for the landing page in multi-page categories

The first I just find to be simpler and nicer to read, especially in urls. The second mostly comes down to the mobile experience and disambiguation. Mostly I don't like seeing the category name duplicated in the mobile nav:

Screen Shot 2020-05-04 at 1 10 27 PM

And I do think there's a tension on these pages, since you don't want them to have the `h1` of Overview, but you want to be clear that _all_ the pages in the category are related to that topic and not just the first one. I dunno. Perhaps I could be convinced otherwise!

**Comment by thisisdano** [comment]
Reverted to the title-in-the-sidebar solution and we can work from there to make it better.

**Comment by afeijoo** [comment]
Added https://github.com/uswds/uswds-site/issues/942 for follow-up work.

**Pull request merged**
