### PR TITLE
USWDS - Header: Use recommended markup for site header and navigation

### LINKED ISSUE #1728: USWDS-Site - Bug: Mobile navigation inaccessible to screen reader touch
### Describe the bug

The content inside the mobile header is inaccessible to users navigating the site by screen reader touch (VoiceOver Gestures or TalkBack). This happens because `aria-hidden` is applied to the `.usa-nav` element. 

## Details

From the original issue report: https://github.com/uswds/uswds/issues/4787

> In https://github.com/uswds/uswds/issues/3527, an issue was raised where the mobile navigation dialog was correctly trapping focus, but when using VoiceOver the focus could escape the mobile navigation dialog. This was fixed by adding an aria-hidden attribute to everything except the .usa-header element (but only if that header element is a direct descendant of <body>).

> However, this breaks in 2 scenarios, both of which are being demonstrated on https://designsystem.digital.gov/.

> On https://designsystem.digital.gov/ itself, the mobile navigation contents, .usa-nav, is not a child of the .usa-header element, so .usa-nav is incorrectly getting an aria-hidden attribute. The result is that the focus correctly moves through the mobile navigation dialog when using the TAB key, but it does not when using VoiceOver to view the items in the navigation (e.g. VoiceOver Web Item rotor).

### Steps to reproduce the bug

From the original issue report: https://github.com/uswds/uswds/issues/4787
1. Navigate to https://designsystem.digital.gov/
1. Shrink the page, or zoom in to the point where the mobile navigation styling is activated
1. Tab to and activate the menu button
1. In the developer tools element inspector, note that the <header class="usa-header"> does not have an aria-hidden attribute, but note that the <nav class="usa-nav site-nav sidenav-mobile"> does have an aria-hidden attribute, despite being the content that the user is trying to interact with.

### Expected Behavior

All of the page content has aria-hidden applied to it, EXCEPT for the mobile navigation dialog's content.

This should be the case for a variety of .usa-header and .usa-nav document structures, since there are likely many different structures in the wild at this point.

### Screenshots

_No response_

### System setup

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

**Use recommended header and nav markup.** Header and navigation uses USWDS recommended extended header markup. The previous header/menu was having issues with talk back on android. This uses the latest recommended markup for header. Closes #1728.

### Major changes

- Use classes and markup from [USWDS extended header](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?args=&id=components-header--extended&viewMode=story) markup ⋆
- Site header classes use BEM-style classes
- Removed unused or duplicate styles `uswds-custom.css` - `75KB → 74KB`
- Variables have been moved to custom project settings [04a08be50d3facb9565bfc26e44c160265320e6b]
- Mixins have their own partial now [e8cc4fb88c1f1a4ba88d2c7e8f51832a4cefd8d7]
- Site header styles moved to their own partial [fa1769223863bfe8f54eda2648d9636d3b98e9c9]
- Site search moved to an include [fb99215065df7f1a33794b6f54f48274c14d8a64]
- New dependencies
  - Added concurrently for more reliable parallel tasks [fd7c27ca163767618e79c7c14e583ce58f925cd1]
  - Ran `bundle update` [fd7c27ca163767618e79c7c14e583ce58f925cd1]

⋆ Not exact, because mobile menu needs accordion and desktop needs to be sticky.

#### Mobile

**Before**

designsystem digital gov_

**After**

localhost_4000_

**Before**

designsystem digital gov_ (1)

**After**

localhost_4000_ (1)

#### Desktop

**Before**

image

**After**

image

**Before**

image

**After**

image

### New dependencies

| Name         | Old | New   |
| :------------ | --- | ----- |
| concurrently | ―   | 7.3.0 |

## How to test

- [ ] Mobile menu should visually match production
- [ ] Desktop menu should visually match production
- [ ] Next report styles should be unaffected and look the same as production
- [ ] SASS should compile successfully
- [ ] Search should continue to function

---

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by amyleadem — CHANGES_REQUESTED** [review]
Discoveries:
- The hover states on the GitHub button are different:
    image
- Different padding on items at desktop width - improved alignment on individual elements but `.usa-nav__secondary` as a whole might be slightly off center vertically. 
- Flagging for awareness: I noticed that the `data-nav-hidden` and `aria-hidden` attributes are still being added to `.usa-nav` since it lives outside `.usa-header`. This should be resolved with the update in https://github.com/uswds/uswds/pull/4892.

Ran the following scripts successfully:
- [x] npm install
- [x] npm run build
- [x] npm start

- [ ] npm test 
  - Tests did not pass at this time because of issues that appeared after `bundle update`. This should be able to pass once we merge https://github.com/uswds/uswds-site/pull/1735

Visual testing: 
- [x] Chrome, Firefox, Safari, iOS Safari, Edge for MacOS
- [x] Mobile and desktop widths
- [x] Checked both Next and standard styles

**Comment by mejiaj** [comment]
@amyleadem thanks for catching these bugs, I've added some fixes.

---

> * The hover states on the GitHub button are different:
>   image

Fixed in [cdbb38b](https://github.com/uswds/uswds-site/pull/1730/commits/cdbb38b33f026b0d310713581d9464e05d04e20b)

---

> * Different padding on items at desktop width - improved alignment on individual elements but `.usa-nav__secondary` as a whole might be slightly off center vertically.

Fixed in [0679593](https://github.com/uswds/uswds-site/pull/1730/commits/06795938ce0633ac04b103d49110295914dccdb8)

**Review by amyleadem — CHANGES_REQUESTED** [review]
Nice work! The fixes look great. 

I did find one more alignment issue in Next when performing another visual check. 

image

Also, I found some merge conflicts (mostly around `type="button"`) when I pulled in main. Other than that, looking good.

**Comment by mejiaj** [comment]
@amyleadem thanks for the great feedback.

- Updated next report logo indents
- Added `type="button"` to the nav opener/closers

**Review by amyleadem — APPROVED** [review]
Looks good! Nice work.

**Review by thisisdano — APPROVED** [review]
Excellent refactor and review. Bravo!

**Pull request merged**
