### PR TITLE
USWDS-Site: Instructions for migrating from USWDS 1.x

### LINKED ISSUE #1733: Update 3.0 Migration guide to include instructions for 1.x
Possible solutions: 
- Include a heads up notice at the start of the migration guide.
- Add an additional panel in section 4 "If you are using USWDS 1.x" (or similar) that reiterates checking out the 2.0 migration guide

Related discussion: https://github.com/uswds/uswds/discussions/4895#discussioncomment-3318185

### PR DESCRIPTION
**Pull request by amyleadem**
## Summary
**Added clarity for users migrating from USWDS 1 to USWDS.** We included a note at the top of the 3.0 Migration guide explaining that users updating from 1.x should first update to version 2 via the 2.0 Migration guide. 

## Related issue
Closes #1733 

Related discussion: https://github.com/uswds/uswds/discussions/4895

## Preview link
Preview link: [Migrating to 3.0](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-migration-1x/documentation/migration/)

## Problem statement
Users should be able to easily find all the needed instructions for upgrading any version of USWDS to version 3. However, users who are upgrading from 1.x do not have clear instructions for all the steps they need to take to get to 3.x. 

## Solution
Providing instructions to 1.x users that they must first follow instructions in the 2.0 migration will help clarify the path to get to version 3. 

Possible additional solution not included in this PR: Add an additional note in [Section 4 of the 3.0 migration guide](https://designsystem.digital.gov/documentation/migration/#4-integrate-any-recent-uswds-changes). I left this out because the initial note clarifies that this is only for migrations from 2 to 3, and additional instructions felt unnecessary. Please let me know if you believe this would be a helpful addition. 

## Testing and review
To review:
1. Confirm that the instructions provided are clear and comprehensive enough that 1.x users can successfully upgrade to USWDS 3. 
1. Proof the copy for any errors

---

Before opening this PR, make sure you’ve done whichever of these applies to you:
- [x] Run `git pull origin [base branch]` to pull in the most recent updates from your base and check for merge conflicts. (Often, the base branch is `develop`).
- [x] Run `npm test` and confirm that all tests pass.

### CODE REVIEW

**Review by bonnieAcameron — CHANGES_REQUESTED** [review]
Hi Amy! This looks great. Can we add a small bit about how someone can tell what version they are on? So it could be like:

Note: This guide provides instructions for upgrading from USWDS 2 to USWDS 3. If your project uses USWDS 1, you will need to update according to the [USWDS 2.0 migration guide](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-migration-1x/documentation/migration-v2) before proceeding with these steps. [Not sure what version you're on? Here's how to check. ](https://designsystem.digital.gov/documentation/migration/#1-check-your-current-uswds-code-and-settings-versions)

**Comment by amyleadem** [comment]
> Hi Amy! This looks great. Can we add a small bit about how someone can tell what version they are on? So it could be like:
> 
> Note: This guide provides instructions for upgrading from USWDS 2 to USWDS 3. If your project uses USWDS 1, you will need to update according to the [USWDS 2.0 migration guide](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/al-migration-1x/documentation/migration-v2) before proceeding with these steps. [Not sure what version you're on? Here's how to check. ](https://designsystem.digital.gov/documentation/migration/#1-check-your-current-uswds-code-and-settings-versions)

@bonnieAcameron Great suggestion! I added this copy in commit [a0b0f6c](https://github.com/uswds/uswds-site/pull/1739/commits/a0b0f6c2dd6b26b1d5808c9820b1bc1adbddc3a0)

**Review by bonnieAcameron — APPROVED** [review]
Looks great! Checked for typos and clarity.

**Review by mejiaj — APPROVED** [review]
Looks good!

I was able to verify the information is correct and all links work.

**Review by thisisdano — APPROVED** [review]

**Comment by Elvis-haley** [comment]
I am Justice Amy Coney Barrett.  Elvis Haley is a Navy Zero.

**Pull request merged**
