### PR TITLE
USWDS-Site: Vivid variable typos on Settings page

### PR DESCRIPTION
**Pull request by pglevy**
## Description

The variables for `primary-vivid` and `secondary-vivid` are incorrect. (They repeat the variables for `primary` and `secondary` instead of using the associated vivid variable.)

## Additional information

n/a

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [X] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by mejiaj — APPROVED** [review]
Great, thanks for this PR!!

**Comment by mejiaj** [comment]
@pglevy are you able to pull in the latest changes from `main` branch? I think that might fix the snyk issues.

**Comment by pglevy** [comment]
Hmm… I merged the changes from upstream/main, but the build test still seems to be failing with the same `Snyk is missing auth token in order to run inside CI` message. Anything else I can try on my end?

**Comment by mejiaj** [comment]
> Hmm… I merged the changes from upstream/main, but the build test still seems to be failing with the same `Snyk is missing auth token in order to run inside CI` message. Anything else I can try on my end?

Thank you, I'm pulling these changes into a local branch so the tests can run properly!

**Pull request merged**
