### PR TITLE
USWDS-Site - Showcase: Add NASA's General Coordinates Network to the showcase

### PR DESCRIPTION
**Pull request by lpsinger**
The General Coordinates Network (GCN) is a public collaboration platform run by NASA for the astronomy research community to share alerts and rapid communications about high-energy, multimessenger, and transient phenomena.

### CODE REVIEW

**Review by mahoneycm — APPROVED** [review]
Lgtm!

- [x] Link follows standard formatting and is in alphabetical order
- [x] Link directs to GCN page as expected
- [x] No build errors
- [x] No proofing errors

**Review by amyleadem — APPROVED** [review]
This looks good to me. Thanks for submitting this!

**Review by mejiaj — APPROVED** [review]
Thanks for adding, confirming this is a unique link.

**Comment by lpsinger** [comment]
> Thanks for adding, confirming this is a unique link.

I'm sorry, what do you mean by "unique link"?

**Comment by lpsinger** [comment]
Any updates on this?

**Comment by mejiaj** [comment]
@lpsinger I was referencing that this is a new (not duplicate) link we can add to the showcase.

Added @thisisdano as reviewer.

**Review by thisisdano — APPROVED** [review]
Thank you!

**Pull request merged**
