### PR TITLE
USWDS - Links: Update external links based on guidance.

### LINKED ISSUE #1203: Update site external links
Use regex search to find and update site external links to reflect updated link guidance

### PR DESCRIPTION
**Pull request by mejiaj**
## Description

Closes #1203. Updates external links to better match [Link guidance](https://designsystem.digital.gov/components/link/#link-guidance).

This PR updates:
- [Component pages](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/components/overview/) 6f7f999
- [About pages ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/about/) 2de8206
- [Templates ](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/templates/) a9d3b64
- [Documentation pages](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/how-to-use-uswds/) 51add9d
- [Design asset CTAs](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/designers/) e0d6a1e
- [Implementations page](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/implementations/) 1abd86b
- [Design Principles](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/design-principles/), [Color tokens](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/design-tokens/color/overview/), and [UI Component](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/components/packages/) pages f9ce83b
- [Blog links](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/about/updates/) 924beb3
- Internal docs like CONTRIBUTING & README 0d5c207
- [Next report](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/next/) 65895c9

Additional links based on USWDS doc updates:
- [Showcase](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/getting-started/showcase/all/) - [Changes →](https://github.com/uswds/uswds/pull/4148/files#diff-2bd0c894b53a1597b9b6d7a2ae564d4c7687530cdd790c9d48d6b446cdd0c21f)
- [Download](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/download/) -   Has github link, also links to same doc as Security.
- [For Developers](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/developers/) -  [Changes →](https://github.com/uswds/uswds/pull/4148/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
- [Code Guidelines](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/code-guidelines/) - [Changes →](https://github.com/uswds/uswds/pull/4148/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055)
- [Security](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/security) - [Changes →](https://github.com/uswds/uswds/pull/4148/files#diff-f6ed156e4bf5c791680662464b94ea5d753f219ee816b385f67870e2c0d7d4c7)

## Additional information

Also adds a new checklist item to the PR template 3361bbc.

⚠ There's also the broken link found in this [comment](https://github.com/uswds/uswds-site/issues/1203#issuecomment-814359983). I wasn't able to find the article after an initial search. Do we want to replace or remove completely?

---

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [x] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by KMullan944 — COMMENTED** [review]
**Components section** 

- File input page has dupe language, "mozilla.org": https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/components/file-input/ 
Pls delete the one that is outside the URL.

- On the Header page, https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/components/header/,  need to fix two external links as bracketed site domain in the Accessibility section: https://webaim.org/techniques/skipnav/   and http://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/ . Also, a bit further down the page, need to bracket external link to https://https.cio.gov/  . PLUS, these 2 references:  
https://www.nngroup.com/articles/menu-design/
https://www.usertesting.com/blog/2015/03/19/site-navigation-tree-testing/

- Wonky link in Step Indicator page that needs fixing probably: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/components/step-indicator/  -- see this section: "Provide navigation separately. Use navigation like a button group/preview/uswds/uswds-site/jm-update-external-links/components/button-group to step forward and backward through a form."

**About section**

- In the Research page, https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/about/research/  these external links as References should be bracketed: 
https://www.nngroup.com/articles/analytics-reports-ux-strategists/
http://www.uxbooth.com/articles/an-analytics-first-approach-to-ux-part-1/

- In the Security section, several of those external links (GSA, Snyk, Github, etc.) need bracketed links added to URLs:  https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/about/security/

**Templates section**

- In Authentication page, add brackets to Login.gov link: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/templates/authentication-pages/

**How to use USWDS section**

-  In "For Developers" section/CSS architecture subsection, several brackets missing in external URLs (Sass, 18F, BEM): https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/developers/
- Also missing brackets in external URLs for "Browser support," "Accessibility," "Fractal" and several other sections of that page above. Could you revisit that section, James?

**How to use USWDS section**

- In Maturity Model page, pls add bracketed element to external URLs that are missing them in "Level 3: What to Do" section: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/maturity-model/
- Also, this seems to be missing several external URL brackets, all throughout the page: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/developers/
- In Performance guidelines, "How to track performance," missing some brackets in URLs: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/performance/how/ 
- In Speed Index section, update URLs with brackets for external links that are missing them: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/performance/glossary/
- in HTTP/2 Performance Guide section, several missing bracketed URL external references to fill in: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/performance/http2/ 
- Code Guidelines section needs several missing bracketed URL external references filled in (basically all the externals on this page): https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/code-guidelines/

**On Implementations page**

- Fix external link to include URL, https://labs.gsa.gov:  https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/documentation/implementations/ 

**Color tokens page**

- Fix the References section at bottom of page to update all external URLs with bracketed links to main page

**Blog-links (News/updates) section**

- Several of these blogs have external links that need brackets in URL updated, not sure how you want to fix universally

**Next report**

- I think we should be fine here unless you want to update all those footnotes with brackets in URL? All seem to be external links. Thanks!

**Comment by mejiaj** [comment]
> In the Security section, several of those external links (GSA, Snyk, Github, etc.) need bracketed links added to URLs: https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/jm-update-external-links/about/security/

This will be resolved by https://github.com/uswds/uswds/pull/4148

**Comment by thisisdano** [comment]
Since our link guidance is in flux, this PR needs to be held

**Comment by mejiaj** [comment]
Closing this as other PRs have taken its place.

**Pull request closed without merging**
