### PR TITLE
Update accessibility.md

### PR DESCRIPTION
**Pull request by finekatie**
Deleted extra period on Identifier page under Accessibility guidance section.
Closes [#2468](https://github.com/uswds/uswds-site/issues/2468)

### CODE REVIEW

**Review by mahoneycm — APPROVED** [review]
Looks good to me!  Sentance no longer has extra period.

```diff
- ...alt text for each logo image you add..
+ ...alt text for each logo image you add.
```

[Preview identifier page →](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.sites.pages.cloud.gov/preview/uswds/uswds-site/kf-identifier-fix-period/components/identifier/)

@mejiaj Are you able to approve and merge since Dan is out?

**Review by mejiaj — APPROVED** [review]
LGTM

**Comment by finekatie** [comment]
This continues to fail checks (I think it's a11y-related stalls) and needs fed final review.

**Comment by mahoneycm** [comment]
@finekatie I reran the failed test and it ran successfully! 👍

**Pull request merged**
