### PR TITLE
Adding Screen Reader instructions to Date Picker guidance

### PR DESCRIPTION
**Pull request by brunerae**
## Preview link
[Date picker accessibility guidance](https://federalist-ead78f8d-8948-417c-a957-c21ec5617a57.app.cloud.gov/preview/uswds/uswds-site/datepicker-a11y-instructions/components/date-picker/#accessibility-date-picker)

## Description

Per comments in https://github.com/uswds/uswds/issues/4271, screen reader instructions are skippable. We are now including them in the `Accessibility` section of guidance. Closes https://github.com/uswds/uswds-site/issues/1636

Before you hit Submit, make sure you’ve done whichever of these applies to you:

- [ ] Follow the [18F Front End Coding Style Guide](https://pages.18f.gov/frontend/) and [Accessibility Guide](https://pages.18f.gov/accessibility/checklist/).
- [ ] Run `npm test` and make sure the tests for the files you have changed have passed.
- [ ] Run your code through [HTML_CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/) and make sure it’s error free.
- [ ] Title your pull request using this format: [Website] - [UI component]: Brief statement describing what this pull request solves.

### CODE REVIEW

**Review by bonnieAcameron — CHANGES_REQUESTED** [review]
Looks great! I removed the brackets since after discussing with Ashley it seemed like we don't want them to display within the text.

**Review by mejiaj — CHANGES_REQUESTED** [review]
Added a suggestion to improve clarity since this is additional information, not an added feature.

**Review by mejiaj — APPROVED** [review]

**Review by bonnieAcameron — DISMISSED** [review]
Hi @mejiaj! I want to introduce a bit more parallel structure to the list of instructions. So it would look like: 

- Days: <kbd>left</kbd> and <kbd>right</kbd> arrow keys
  - Weeks: <kbd>up</kbd> and <kbd>down</kbd> arrow keys
  - Months: use <kbd>page up</kbd> and <kbd>page down</kbd>
  - Years: use <kbd>shift + page up</kbd> and <kbd>shift + page down</kbd>
  - Beginning/End of week: use <kbd>home</kbd> and <kbd>end</kbd> keys

**Comment by amyleadem** [comment]
Looks good!
I wonder if we should add instructions for those using Mac keyboards (at least smaller ones without page up, page down, home, etc keys), because it does require some translation to get this to work on my laptop. 

Translation for Mac:
Months: fn + up arrow, fn + down arrow
Years: shift + fn + up arrow,  shift + fn + down arrow
Beginning/End of week: fn + left arrow, fn + right arrow

**Review by thisisdano — APPROVED** [review]

**Pull request merged**
